name: Deploy2Nekoweb

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v3
        with:
          node-version: current

      - run: npm install

      - run: npm ci

      -  run: npx @11ty/eleventy
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          cleanup: true
          nekoweb-domain: 'web-surfer.nekoweb.org'
          nekoweb-username: 'web-surfer'
          directory: '_site'
          