name: Deploy2Nekoweb

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npx @11ty/eleventy
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          cleanup: true
          nekoweb-domain: web-surfer.nekoweb.org
          nekoweb-username: web-surfer
          directory: _site
          